# Generated by Django 5.0 on 2024-09-01 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=300)),
                ('narxi', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Shaxar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rayon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=300)),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mahsulot')),
            ],
        ),
        migrations.CreateModel(
            name='Korinish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=300)),
                ('rayon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.rayon')),
            ],
        ),
        migrations.AddField(
            model_name='mahsulot',
            name='shaxar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.shaxar'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=8, unique=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('payment_received', models.BooleanField(default=False)),
                ('admin_confirmed', models.BooleanField(default=False)),
                ('payment_amount', models.IntegerField(blank=True, null=True)),
                ('receipt_photo', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('korinish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.korinish')),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mahsulot')),
                ('rayon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.rayon')),
                ('shaxar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.shaxar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
