# Generated by Django 5.0 on 2024-09-02 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_order_receipt_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='admin_confirmed',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_received',
        ),
        migrations.RemoveField(
            model_name='order',
            name='receipt_photo',
        ),
        migrations.AddField(
            model_name='order',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
