# Generated by Django 5.0 on 2024-09-02 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_order_admin_confirmed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=300)),
                ('card_number', models.CharField(max_length=300)),
                ('card_user', models.CharField(max_length=300)),
            ],
        ),
    ]
